web:
  image: golang:1.10-alpine
  working_dir: /go/src/github.com/ecosia/women-who-go
  volumes:
    - .:/go/src/github.com/ecosia/women-who-go
  environment:
    - GOPATH=/go
    - PORT=9999
    - WWO_API_KEY=41eb165aa5014c43a72161812182202
  command: go run cmd/weather-widget/main.go
  ports:
    - 9999:9999
