web:
  image: golang:1.10
  working_dir: /go/src/github.com/wwgberlin/go-weather-widget
  volumes:
    - .:/go/src/github.com/wwgberlin/go-weather-widget
  command: bash -c "go test ./... && go build . && ./go-weather-widget -port=8080 -api_key=f4c3312c49714b8b98e102208181804"
  ports:
    - 8080:8080
